### ISSUE TITLE
DOC:  Need to add how to find SVG icons code

### ISSUE THREAD

**Issue by priyankarpal** [pbclife/gitopener.vercel.app#126]
In the documentation, we need to add how a user can find the SVG icons code
- Mention in the guide that we will use https://simpleicons.org website to find SVG icons code
- You can use another website.
## Folder Structure 

- In the red block area there will be a guide link where you need to mention how to copy & paste the SVG icons (for newbies) 
- Create a `.mdx file` into the `docs/guides/starting-contribution/` named it `how-to-add-SVG-icons.mdx` (exact same)
- Create a PR & wait for merge.
 
![image](https://user-images.githubusercontent.com/88102392/227303119-7344f79c-86b9-4c16-b405-92ff56db417c.png)

**Comment by priyankarpal** [comment]
> Can I work on this?

Yeah sure. Assigned to you.

**Comment by ArslanYM** [comment]
@priyankarpal  Like this right?
![image](https://user-images.githubusercontent.com/104521101/228301985-a5c3e01e-0266-4952-b71d-734cfb1f746e.png)

**Comment by priyankarpal** [comment]
> @priyankarpal Like this right? ![image](https://user-images.githubusercontent.com/104521101/228301985-a5c3e01e-0266-4952-b71d-734cfb1f746e.png)

yeah.Looks Good 🎉 also share whole doc

**Comment by ArslanYM** [comment]
@priyankarpal  also the guide should just state how to copy and paste svgs , not what svgs are etc?

**Comment by ArslanYM** [comment]
Hey , I'm not getting the option for creating  a PR?

**Comment by ArslanYM** [comment]
> > Hey , I'm not getting the option for creating a PR?
> 
> why? are you in the code editor?

I did the normal procedure , made a new branch , did my changes , commited and pushed to the new branch on my fork. But the change is not displaying for some reason

**Comment by priyankarpal** [comment]
> > > Hey , I'm not getting the option for creating a PR?
> > 
> > 
> > why? are you in the code editor?
> 
> I did the normal procedure , made a new branch , did my changes , commited and pushed to the new branch on my fork. But the change is not displaying for some reason

have you ever set upstream command?

**Comment by priyankarpal** [comment]
> yeah i set the upstream command as well

could you share screenshots?

**Comment by ArslanYM** [comment]
commit:
![commm](https://user-images.githubusercontent.com/104521101/229014903-bcdf581a-45f6-4678-b8a5-f00050b1dd3e.png)

I think this is the issue. Im making the changes but they arent being commited because of lint error.
Can you tell me how i should write the commit code. I am not familiar with husky

**Comment by priyankarpal** [comment]
> commit: ![commm](https://user-images.githubusercontent.com/104521101/229014903-bcdf581a-45f6-4678-b8a5-f00050b1dd3e.png)
> 
> I think this is the issue. Im making the changes but they arent being commited because of lint error. Can you tell me how i should write the commit code. I am not familiar with husky

you need to add a proper title. such as `"docs: added svg icon page"`

**Comment by priyankarpal** [comment]
@sboy99 please check

**Comment by sboy99** [comment]
use `docs:` instead of `docs :`

**Comment by suzy-g38** [comment]
@ArslanYM if your problem is solved congrats otherwise, you can follow this document, which helped me: https://www.conventionalcommits.org/en/v1.0.0-beta.2/#why-use-conventional-commits.

**Comment by suzy-g38** [comment]
@sboy99 @priyankarpal don't you think adding some examples in the "How to write professional commits ?" section, can give some extra clarity?

**Comment by sboy99** [comment]
> @sboy99 @priyankarpal don't you think adding some examples in the "How to write professional commits ?" section, can give some extra clarity?

Yes that is also a part of the documentation create a folder inside guides `best practice` and we can write best practices as well

**Comment by suzy-g38** [comment]
> > @sboy99 @priyankarpal don't you think adding some examples in the "How to write professional commits ?" section, can give some extra clarity?
> 
> Yes that is also a part of the documentation create a folder inside guides `best practice` and we can write best practices as well

Why create another folder when we can add them in the "How to write professional commits. mdx" file. Because if you check the "Here are some examples of good commit messages:" part those are actually the definitions of the terminology we use mostly like feat, fix, docs etc, but not the examples of commit messages. So if you create a part like "definitions of the terminologies" and then examples, don't you think that will be a good option?

**Comment by sboy99** [comment]
Professional commits are useful to identify the type of work or change is being made. Additionally it supports automated releases. In software development most of the changes can be broken down into `adding features` `fixing bugs` `doing a task` `performance optimization` `ci cd` etc. So to trigger this you can break your commit message into two. 

> `sub: message` 

In the field of subject you can and conventions such as `feat`  `fix` `chore` `refactor` etc. You can better check in the commitlint file. And followed by a suitable message. Thats it.

**Comment by sboy99** [comment]
Di

> > > @sboy99 @priyankarpal don't you think adding some examples in the "How to write professional commits ?" section, can give some extra clarity?
> > 
> > 
> > Yes that is also a part of the documentation create a folder inside guides `best practice` and we can write best practices as well
> 
> Why create another folder when we can add them in the "How to write professional commits. mdx" file. Because if you check the "Here are some examples of good commit messages:" part those are actually the definitions of the terminology we use mostly like feat, fix, docs etc, but not the examples of commit messages. So if you create a part like "definitions of the terminologies" and then examples, don't you think that will be a good option?

Yup, we can do that as well

**Comment by suzy-g38** [comment]
> Di
> 
> > > > @sboy99 @priyankarpal don't you think adding some examples in the "How to write professional commits ?" section, can give some extra clarity?
> > > 
> > > 
> > > Yes that is also a part of the documentation create a folder inside guides `best practice` and we can write best practices as well
> > 
> > 
> > Why create another folder when we can add them in the "How to write professional commits. mdx" file. Because if you check the "Here are some examples of good commit messages:" part those are actually the definitions of the terminology we use mostly like feat, fix, docs etc, but not the examples of commit messages. So if you create a part like "definitions of the terminologies" and then examples, don't you think that will be a good option?
> 
> Yup, we can do that as well

If you assign me I can do that.

**Comment by sboy99** [comment]
> If you assign me I can do 
 It is assigned to you. Add a comment in #139

**Comment by priyankarpal** [comment]
@ArslanYM are you working on this issue?

**Comment by ArslanYM** [comment]
No im not

**Comment by suzy-g38** [comment]
> No im not 
 
Hey if you don't want to work on this issue, @priyankarpal can I work on this one?

**Comment by priyankarpal** [comment]
> > No im not
> 
> Hey if you don't want to work on this issue, @priyankarpal can I work on this one?

You can work on it 🤝 @suzy-g38

**Comment by suzy-g38** [comment]
> use this trick & just paste the link.

Cool man loved it.
