### ISSUE TITLE
DOC: Update README.md

### ISSUE THREAD

**Issue by priyankarpal** [pbclife/gitopener.vercel.app#127]
- Need to update README.md file with latest images from GitOpener website.
- Add images by drag & drop 
- Add emojis
- Add some descriptions about Contributors, LICENSE etc.

**Comment by gulshanpr** [comment]
Hey, I got you what I need to do to contribute to this issue, could you assign me.

**Comment by priyankarpal** [comment]
> Hey, I got you what I need to do to contribute to this issue, could you assign me.

Assigned to you.

**Comment by AshwanthramKL** [comment]
Hey @priyankarpal, can I try my hand at this?

**Comment by priyankarpal** [comment]
@gulshanpr are you working on this issue?

**Comment by gulshanpr** [comment]
> Hey @priyankarpal, can I try my hand at this?

You can work on it, I unassigned myself,

**Comment by priyankarpal** [comment]
> Hey @priyankarpal, can I try my hand at this?

assigned to you.

**Comment by AshwanthramKL** [comment]
Hey @priyankarpal, Could you clarify what you mean by "Add images by drag & drop"

> * Need to update README.md file with latest images from GitOpener website.
> * Add images by drag & drop
> * Add emojis
> * Add some descriptions about Contributors, LICENSE etc.

**Comment by priyankarpal** [comment]
> Hey @priyankarpal, Could you clarify what you mean by "Add images by drag & drop"
> 
> > * Need to update README.md file with latest images from GitOpener website.
> > * Add images by drag & drop
> > * Add emojis
> > * Add some descriptions about Contributors, LICENSE etc.
> 
> 

Paste image link. (eg. https://user-images.githubusercontent.com/18360871/199210192-f5599a23-f0b1-49ff-9c52-2554a72a2c14.png)
