### ISSUE TITLE
DOC: How to write professional commits

### ISSUE THREAD

**Issue by sboy99** [pbclife/gitopener.vercel.app#139]
Write how to commit like a pro. Best commit conversations and how they are useful with example.

**Comment by suzy-g38** [comment]
Okay, Thanks.

**Comment by priyankarpal** [comment]
> Write how to commit like a pro. Best commit conversations and how they are useful with example.

We already have the best [commit conversations](https://gitopener.vercel.app/guides/general-terminology/How-to-write-professional-commits). Just we need to add some examples.

**Comment by suzy-g38** [comment]
> > Write how to commit like a pro. Best commit conversations and how they are useful with example.
> 
> We already have the best [commit conversations](https://gitopener.vercel.app/guides/general-terminology/How-to-write-professional-commits). Just we need to add some examples.
Hey, I added some extra stuff and restructured some points in my own way, apart from adding some examples. I am really sorry. I did that completely on my own without asking you guys. Just forgot that I am contributing to an open source, really sorry. Do you want to see it first or I will delete those parts.

**Comment by priyankarpal** [comment]
> > > Write how to commit like a pro. Best commit conversations and how they are useful with example.
> > 
> > 
> > We already have the best [commit conversations](https://gitopener.vercel.app/guides/general-terminology/How-to-write-professional-commits). Just we need to add some examples.
> 
> Hey, I added some extra stuff and restructured some points in my own way, apart from adding some examples. I am really sorry. I did that completely on my own without asking you guys. Just forgot that I am contributing to an open source, really sorry. Do you want to see it first or I will delete those parts.

If you have already completed the task, please feel free to share the demo with us.

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
