### ISSUE TITLE
Feat: Add cursot pointer

### ISSUE THREAD

**Issue by priyankarpal** [pbclife/gitopener.vercel.app#142]
### Description

Need to add a cursor pointer in the button.

![image](https://user-images.githubusercontent.com/88102392/229326463-88adb37f-325d-4711-8136-b35273a86c56.png)

**Comment by sboy99** [comment]
This is disabled right now. Cause you can sync your profile once in two days. If you your profile got updated before two days it will automatically active

**Comment by priyankarpal** [comment]
> This is disabled right now. Cause you can sync your profile once in two days. If you your profile got updated before two days it will automatically active

ok
