### ISSUE TITLE
Dark Theme is not loading propely

### ISSUE THREAD

**Issue by suzy-g38** [pbclife/gitopener.vercel.app#144]
Whenever you choose the dark theme and refresh the page then the light theme is showing first, then the dark theme. Same with the 'Sync With System' option.

**Comment by priyankarpal** [comment]
> ### What would you like to share or ask?
> Whenever you choose the dark theme and refresh the page then the light theme is showing first, then the dark theme. Same with the 'Sync With System' option.

Yes, 

https://user-images.githubusercontent.com/88102392/229866786-9bd4c2bd-03b9-4a90-b03e-7c9f40da37ac.mp4

**Comment by suzy-g38** [comment]
> > ### What would you like to share or ask?
> > Whenever you choose the dark theme and refresh the page then the light theme is showing first, then the dark theme. Same with the 'Sync With System' option.
> 
> Yes,

Would you like to assign me?

**Comment by priyankarpal** [comment]
> > > ### What would you like to share or ask?
> > > Whenever you choose the dark theme and refresh the page then the light theme is showing first, then the dark theme. Same with the 'Sync With System' option.
> > 
> > 
> > Yes,
> 
> Would you like to assign me?

You can work on it 🤝

**Comment by suzy-g38** [comment]
> > > > ### What would you like to share or ask?
> > > > Whenever you choose the dark theme and refresh the page then the light theme is showing first, then the dark theme. Same with the 'Sync With System' option.
> > > 
> > > 
> > > Yes,
> > 
> > 
> > Would you like to assign me?
> 
> You can work on it 🤝

Thanks
