### ISSUE TITLE
Q: What is pull request ?

### ISSUE THREAD

**Issue by sboy99** [pbclife/gitopener.vercel.app#30]
You can write importance of pull request, why one should consider specific pull request while working with different changes.

**Comment by lavanyayangala** [comment]
1. Pull request helps us to track the changes we made before pushing them to the main branch where we can move to previous track of code if needed.
2. This helps to avoid bugs and other problems that could potentially cause serious issues.
3. They are an essential part of the software development process, helping to ensure that relevant parties review code changes before they are merged into the main codebase.

**Comment by AniketNS** [comment]
Hey @sboy99, assign this to me. I'll create a PR by tomorrow.
