### ISSUE TITLE
Refactor: Optimise code base  

### ISSUE THREAD

**Issue by sboy99** [pbclife/gitopener.vercel.app#36]
### Changes Proposed
- Rename component files using React naming convention
- Using `FC` component instead of simple `function` tag

**Comment by Aadarsh805** [comment]
All the files inside `components` folder need this change.

**Comment by Aadarsh805** [comment]
These are gonna be huge changes, lots of imports will need changes
so let's do it ahead of time, otherwise, it'll become much of a huge work later

**Comment by Aadarsh805** [comment]
```
"Typescript React Function Component": {
    "prefix": "fc",
    "body": [
      "import { FC } from 'react'",
      "",
      "interface ${TM_FILENAME_BASE}Props {",
      "  $1",
      "}",
      "",
      "const $TM_FILENAME_BASE: FC<${TM_FILENAME_BASE}Props> = ({$2}) => {",
      "  return <div>$TM_FILENAME_BASE</div>",
      "}",
      "",
      "export default $TM_FILENAME_BASE"
    ],
    "description": "Typescript React Function Component"
  },
```
Here's a vscode snippet to crate typescript FC components using emmet
