### ISSUE TITLE
Fix: Make separate Favicons for light and dark theme

### ISSUE THREAD

**Issue by Aadarsh805** [pbclife/gitopener.vercel.app#72]
### Description

Make separate Favicons for light and dark theme
we have one right here `/public/favicon-dark.svg`

**Comment by Shivam-Amin** [comment]
- Can I work on this issue?

**Comment by Aadarsh805** [comment]
> * Can I work on this issue?

sure @Shivam-Amin go ahead

**Comment by Shivam-Amin** [comment]
I think this issue is already fixed, isn't it?

![Screenshot 2023-03-14 193009](https://user-images.githubusercontent.com/106419448/225026042-0bd3d641-1457-44b3-b18b-1b292ca2a8a1.png)
