### ISSUE TITLE
Feat: add social links in contributor profile page

### ISSUE THREAD

**Issue by sboy99** [pbclife/gitopener.vercel.app#84]
### Description

Currently, social links are not working as they are not plugged in. Retrieve social links from contribution meta data and add as link component and render respective icon.

**Comment by Shivam-Amin** [comment]
I would love to work on this issue.
But I only know html, css & js & not any frameworks yet.
- So, can you guide me, what do I need to learn to contribute to this issue?

**Comment by sboy99** [comment]
This issue is fixed yesterday. But there are some other social links that a contributor can share such as reddit, artstation, behance etc. Add those. The only thing you have to do is add the social field name inside `src>types>client>Contributors.ts` and create the respective icon component inside `src>components>icons>socials`. There are so many examples, have a look at how it is designed and create an Icon. I highly recommend [Simple Icons](https://simpleicons.org/). Next, add the entry to allowedComponents `src>components>contributorProfilePage`, remember the array index is the priority of social links

**Comment by priyankarpal** [comment]
So this issue is fixed. I'm closing this issue.
