### ISSUE TITLE
Bug: Scroll not working

### ISSUE THREAD

**Issue by himanshu1221** [pbclife/gitopener.vercel.app#98]
### Is there any existing issue for this?

- [X] I have searched the existing issues

### Description

When we are trying to hold to scroller and trying to pull it down it not going down the onto

### Screenshots

[[BUG] git_opener.webm](https://user-images.githubusercontent.com/32031706/226156828-db01c103-a6ba-4782-b42c-907d16307e29.webm)

### What browser are you seeing the problem on?

Chrome

**Comment by sboy99** [comment]
Do you want to fix this issue?

**Comment by himanshu1221** [comment]
> Do you want to fix this issue?

Sure !
I will give it a try 💯

**Comment by priyankarpal** [comment]
but it's working now.

https://user-images.githubusercontent.com/88102392/226159418-834a99c0-1c8d-4e30-8473-5101eafe698e.mp4

**Comment by himanshu1221** [comment]
> but it's working now.

It is still not working in my browser

**Comment by himanshu1221** [comment]
> > > but it's working now.
> > 
> > 
> > It is still not working in my browser
> 
> ok ok. Currently, I'm using Brave. Try to restart your browser

yes it's working now 

thanks for helping out
